imports:
  # Content
  # -> Hugolify content types and taxonomies available https://www.hugolify.io/docs/sections/
  - path: github.com/hugolify/hugolify-sveltia-cms
  - path: github.com/hugolify/hugolify-posts-categories
  - path: github.com/hugolify/hugolify-posts
  # Core theme
  - path: github.com/hugolify/hugolify-theme

  # CMS
  - path: github.com/hugolify/hugolify-admin
