admin:
  cms: sveltiacms # set Sveltia CMS as CMS for Hugolify
  repo: Hugolify/hugolify-demo-sveltiacms # set your repositoryâ€™s url
  collections:
    indexes:
      enable: false # disable unused collection
